version: '3'

services:
  app:
    build: ./
    container_name: "prepise-back"
    image: prepise-back

    ports:
      - "8080:8080"

    links:
      - redis:redis

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production

    volumes:
      - "C:/Users/ulano/Desktop/Site/fullstack/Prepise/app/server:/app"

  redis:
    container_name: "redis"
    image: redis:latest

    ports:
      - "6379:6379"

    volumes:
      - "C:/Users/ulano/Desktop/Site/fullstack/Prepise/app/server:/data"
